spring:
  application:
    name: livemenu

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/livemenu_db}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

  security:
    user:
      name: ${ADMIN_USERNAME:livemenu}
      password: ${ADMIN_PASSWORD:admin}
    jwt:
      secret: ${JWT_SECRET:local_dev_secret_key_make_it_long_enough_32_chars}
      expiration: 86400000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm.results.graph.AST: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

cloudinary:
  url: ${CN_URL:cloudinary://api_key:api_secret@cloud_name}