spring:
  application:
    name: livemenu

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/livemenu_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    username: ${ADMIN_USERNAME:livemenu}
    password: ${ADMIN_PASSWORD:admin}
    jwt:
      secret: ${JWT_SECRET:local_dev_secret_key_make_it_long_enough_32_chars}
      expiration: 86400000

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

cloudinary:
  url: ${CN_URL:cloudinary://api_key:api_secret@cloud_name}

firebase:
  config: ${FIREBASE_CONFIG}