spring:
  application:
    name: livemenu

  datasource:
    url: jdbc:postgresql://localhost:5432/livemenu_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    username: ${ADMIN_USERNAME:livemenu}
    password: ${ADMIN_PASSWORD:admin}
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000

cloudinary:
  url: cloudinary://${CN_KEY}:${CN_SECRET}@${CN_NAME}