spring:
  application:
    name: livemenu

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/livemenu_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    username: ${ADMIN_USERNAME:livemenu}
    password: ${ADMIN_PASSWORD:admin}
    jwt:
      secret: ${JWT_SECRET:local_dev_secret_key_make_it_long_enough_32_chars}
      expiration: 86400000

logging:
  level:
    root: INFO
    com.flykraft.livemenu: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

cloudinary:
  url: ${CN_URL:cloudinary://api_key:api_secret@cloud_name}

firebase:
  config: ${FIREBASE_CONFIG}